import Imag1 from '@/assets/images/hero-image-1.jpg'
import Imag2 from '@/assets/images/hero-image-2.jpg'
import Imag3 from '@/assets/images/hero-image-3.jpg'
import Imag4 from '@/assets/images/hero-image-4.jpg'
import Imag5 from '@/assets/images/hero-image-5.jpg'
import Imag6 from '@/assets/images/hero-image-6.jpg'
import Imag7 from '@/assets/images/hero-image-7.jpg'
